language: java

sudo: required
services:
  - docker
  - xvfb

addons:
  apt:
    packages:
      - fakeroot

install: true

jobs:
  include:
    - stage: "Tests"
      os: linux
      dist: bionic
      jdk: oraclejdk9
      env:
        - _JAVA_OPTIONS="-Dtestfx.robot=glass -Dglass.gtk.uiScale=2.0"
      name: "Unit Tests"
      script: ./gradlew test
    - script: ./gradlew integrationTest -i
      dist: bionic
      jdk: oraclejdk9
      name: "Integration Tests"
    - stage: GitHub Release of Linux build
      os: linux
      dist: bionic
      jdk: oraclejdk9
      env:
        - _JAVA_OPTIONS="-Dtestfx.robot=glass -Dglass.gtk.uiScale=2.0"
      script: ./gradlew jfxNative
      deploy:
        provider: releases
        api_key: $GITHUB_KEY
        file: "build/jfx/native/kafka-browser-1.0.deb"
        skip_cleanup: true
        draft: true
        on:
          tags: true
    - stage: GitHub Release of MacOS build
      os: osx
      osx_image: xcode9.3
      jdk: oraclejdk9
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.verbose=true"
      script: ./gradlew jfxNative
      deploy:
        provider: releases
        api_key: $GITHUB_KEY
        file:
         - "build/jfx/native/kafka-browser-1.0.pkg"
         - "build/jfx/native/kafka-browser-1.0.app"
        skip_cleanup: true
        draft: true
        on:
          tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

after_script:
  - ls -la build/jfx/native
